### ISSUE TITLE
Calculate measure of gains relative to noise for informing future recordings

### ISSUE THREAD

**Issue by talonmyburgh** [COSMIC-SETI/COSMIC-VLA-CalibrationEngine#10]
The idea is to derive the `gains` in the postprocess, apply them to the cross-correlated data, re-derive the gains and calculate a "grade" from them. 

These grades will then ship to the collator downstream to take the mean and inform the observation process of the resultant grade.

**Comment by talonmyburgh** [comment]
This exists but requires input and or a "next-step" before deciding on whether to put into production.

**Comment by talonmyburgh** [comment]
@demorest @Chenoachem please see this [document](https://docs.google.com/document/d/1-y_EZB84v51pr5WAwLt234eXebs4IhAPOadtEbo85C8/edit?usp=sharing).

I've been "applying" the gains to the visibilities using [this](https://github.com/COSMIC-SETI/COSMIC-VLA-CalibrationEngine/blob/main/calib_util.py#L266) function that Savin mentioned works. This is done per subband in the calibration postprocess [here](https://github.com/COSMIC-SETI/COSMIC-VLA-CalibrationEngine/blob/main/calibrate_uvh5.py#L227).

Given the phase and amplitude plots that I show side by side in the document I've linked, it would appear that perhaps these gains are in fact not being applied correctly and are in fact worsening the "spread" in phase and subsequently worsening the projected grade per subband and furthermore the overall projected grade.

I'm a little unfamiliar with this "applycal" function so perhaps if @demorest (who I think may have written the function) could look it over and note if there are any glaring problems?

I largely relied on Savin to do this "gain" application step which he'd said he'd vetted before but perhaps it was not as broadly functional as he might have thought.

**Comment by demorest** [comment]
Hi Talon, I took a quick look, the only thing that has stuck out to me so far is that we should set `phaseonly=True` in the `applycal()` call.  This is for consistency with how we actually apply them.  I don't know for sure if this will fix the issues you are seeing but give it a try and see what happens.  If there is an antenna with very low amplitude (for example ea24 AC here), applying the amplitude is sort of like dividing by zero and could be breaking things.

These functions (both applycal and gaincal) are based on ones I wrote originally but the antenna indexing parts have been modified quite a bit.  It's possible something is messed up in there but even if the data were jumbled it's hard for me to see how the phases would get so bad.

**Comment by talonmyburgh** [comment]
Sigh... good spot @demorest. That worked perfectly. Please see [document](https://docs.google.com/document/d/1-y_EZB84v51pr5WAwLt234eXebs4IhAPOadtEbo85C8/edit?usp=sharing) for proof.

Will update our calibration postprocess to use this argument set to `True`.
