### ISSUE TITLE
`chown`s will fail unless run as COSMIC / root

### ISSUE THREAD

**Issue by jack-h** [COSMIC-SETI/COSMIC-VLA-CalibrationEngine#4]
There is nothing inherent about this script which requires elevated permissions, but the typical use where it writes to HASHPIPE-created, root-owned directories seems to have led to the assumption that it will be running as root itself.

This seems to fail unless the script is running as `root` or as `cosmic`

https://github.com/COSMIC-SETI/COSMIC-VLA-CalibrationEngine/blob/085158e209775463a2b110efe6ff841178cb834d/calibrate_uvh5.py#L877

If possible, it would likely be better to create the new files with an appropriate `umask`, or at the very least make the chown operations command-line controlled (with standard behaviour to not chown at all)

**Comment by talonmyburgh** [comment]
Patched within COSMIC-SETI/COSMIC-Commissioning#52
